const ErrorCodes = {
  EMAIL_EXISTS: "EMAIL_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND: "NOT_FOUND",
  NETWORK_ERROR: "NETWORK_ERROR",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_OBJECTID: "INVALID_OBJECTID",
  CONFLICT: "CONFLICT",
};

export default ErrorCodes;
